### ISSUE TITLE
FileSystem.isDirectory("C:/") returns false

### ISSUE THREAD

**Issue by ProG4mr** [HaxeFoundation/haxe#3266]
Doing 

FileSystem.isDirectory("C:/")

returns false on neko and cpp (windows) targets. while FileSystem.readDirectory("C:/") works fine, should it not return true?

**Comment by Simn** [comment]
It looks like neko's `sys_file_type` is a bit picky when it comes to trailing slashes. It is requires for `C:\` but does not work for `subdir/`.

**Comment by Simn** [comment]
I don't think we can add a test for this particular issue, but it should be fixed.

**Comment by Simn** [comment]
I have reverted my fix because neko didn't like it. I have to figure out what paths it accepts exactly, unless we want to fix this in the neko implementation itself.

**Comment by ncannasse** [comment]
I think it either accept a path such as "c:/path/to/my/dir" (no leading slash) or a drive letter with a slash "c:/"

**Comment by Simn** [comment]
This is a very specific fix and I don't have a graceful fix, so I'm pushing this to 3.3.

**Comment by ProG4mr** [comment]
Okay, thanks, by the way this issue gives me a little more trouble:

https://github.com/HaxeFoundation/haxe/issues/3691

It has been closed but i tested it with haxe 3.2 dev branch and the problem remains, maybe reopen it until someone can fix it? Thanks a lot, i can also create a small test project for it.
