### ISSUE TITLE
Typing time is too long to be normal

### ISSUE THREAD

**Issue by fantoine** [HaxeFoundation/haxe#4840]
Issue imported from [Google Group topic](https://groups.google.com/forum/#!topic/haxelang/116Di6s1_8w).

---

The issue is that I get very long compilation time (especially in the typing part) for a not so-big NodeJs project (10000 LOC for 200 files).

I get those times with haxe 3.2.1:
```
Total time : 12.440s 
------------------------------------ 
   filters : 0.060s, 0% 
   generate js : 0.050s, 0% 
   haxelib : 0.000s, 0% 
   macro execution : 2.380s, 19% 
   other : 1.780s, 14% 
   parsing : 0.210s, 2% 
   typing : 7.960s, 64% 
```

And those with haxe 3.3.0 (nightly):
```
Total time : 12.090s
------------------------------------
  analyzer-cleanup : 0.000s, 0%
  analyzer-filter-apply : 0.000s, 0%
  analyzer-from-texpr : 0.040s, 0%
  analyzer-fusion : 0.010s, 0%
  analyzer-to-texpr : 0.010s, 0%
  filters : 0.090s, 1%
  generate js : 0.060s, 0%
  haxelib : 0.000s, 0%
  macro execution : 2.770s, 23%
  other : 1.490s, 12%
  parsing : 0.310s, 3%
  typing : 7.310s, 60%
```

I don't have so much macro which run on the project so I don't think it's related to this.
The bad part is that I can't reproduce the error on a small project...

---

As I also mentioned in the topic, could it be possible to get some `@:macroTimes` meta to add to macro methods and then get informations about their execution.

I easily imagine something like this:

```haxe
class Macro {
    @:macroTimes('mymacro')
    public static macro function foo() { /* whatever */ } 
}
```

And get stats when using `--times` option:
```
Total time : 12.090s
------------------------------------
  analyzer-cleanup : 0.000s, 0%
  analyzer-filter-apply : 0.000s, 0%
  analyzer-from-texpr : 0.040s, 0%
  analyzer-fusion : 0.010s, 0%
  analyzer-to-texpr : 0.010s, 0%
  filters : 0.090s, 1%
  generate js : 0.060s, 0%
  haxelib : 0.000s, 0%
  macro execution : 2.770s, 23%
  other : 1.490s, 12%
  parsing : 0.310s, 3%
  typing : 7.310s, 60%
  *mymacro : 0.000s, 0% (0 calls)*
```

**Comment by Simn** [comment]
Try `-D macro-times`. It's a bit spammy but maybe it gives you an idea what's going on.

**Comment by ncannasse** [comment]
It's not entirely anormal to get 10s of typing for big projects. The usual answer to that is to use compilation server, but then it seems you get another error, which is the one we should investigate further.

@Simn does this error come from us or some user macro code ?

**Comment by Simn** [comment]
The balance of these numbers is abnormal. If the project was that big, other parts would take longer as well. Look at how little time is spent in filters and the analyzer.

The only typing-related bug I'm aware of is this: https://github.com/HaxeFoundation/haxe/issues/3819#issuecomment-72175310

@ncannasse: What error?

**Comment by fantoine** [comment]
Didn't know about this option :)

Just to give you the macro times details, here it is:
```
Total time : 12.450s
------------------------------------
  analyzer-cleanup : 0.010s, 0%
  analyzer-filter-apply : 0.020s, 0%
  analyzer-from-texpr : 0.010s, 0%
  analyzer-fusion : 0.020s, 0%
  analyzer-to-texpr : 0.000s, 0%
  filters : 0.080s, 1%
  generate js : 0.070s, 1%
  haxelib : 0.000s, 0%
  macro _hxnodejs.VersionWarning.include : 0.000s, 0%
  macro afterGenerate : 0.150s, 1%
  macro fab.Async.build : 0.070s, 1%
  macro fab.Mongoose.emit : 0.000s, 0%
  macro fab.api.db.DatabaseBuilder.addRepositories : 0.000s, 0%
  macro fab.api.db.DatabaseBuilder.build : 0.150s, 1%
  macro fab.api.doc.SwaggerBuilder.addModelPath : 0.000s, 0%
  macro fab.api.doc.SwaggerBuilder.enable : 0.010s, 0%
  macro fab.api.i18n.LocalizatorBuilder.addTranslationPath : 0.000s, 0%
  macro fab.api.i18n.LocalizatorBuilder.build : 0.020s, 0%
  macro fab.api.macro.MacroTools.listClassesName : 0.000s, 0%
  macro fab.api.macro.MacroTools.readFileLines : 0.020s, 0%
  macro fab.api.routing.Route.send : 0.000s, 0%
  macro fab.api.routing.RouterBuilder.addRoutes : 0.000s, 0%
  macro fab.api.routing.RouterBuilder.build : 0.140s, 1%
  macro fab.api.test.TesterBuilder.addFixtures : 0.000s, 0%
  macro fab.api.test.TesterBuilder.addTests : 0.000s, 0%
  macro fab.api.test.TesterBuilder.build : 0.200s, 2%
  macro fab.api.validation.ValidationBuilder.enable : 0.000s, 0%
  macro haxe.macro.Compiler.allowPackage : 0.000s, 0%
  macro haxe.macro.Compiler.keep : 0.010s, 0%
  macro mcli.internal.Macro.build : 0.000s, 0%
  macro minject.Injector.getValue : 0.000s, 0%
  macro minject.Injector.instantiate : 0.000s, 0%
  macro minject.Injector.map : 0.120s, 1%
  macro minject.InjectorMacro.addMetadata : 0.000s, 0%
  macro minject.InjectorMapping.toSingleton : 0.400s, 3%
  macro npm.Include.build : 0.020s, 0%
  macro onGenerate : 0.060s, 0%
  macro tink.SyntaxHub.build : 0.420s, 3%
  macro tink.SyntaxHub.use : 0.000s, 0%
  macro tink.Template.addFlavor : 0.000s, 0%
  macro tink.Template.use : 0.000s, 0%
  macro typing (+init) : 1.290s, 10%
  macro util.CopyMethods.build : 0.000s, 0%
  macro util.Mongoose.buildManager : 0.010s, 0%
  macro util.Mongoose.buildModel : 0.250s, 2%
  other : 2.020s, 16%
  parsing : 0.280s, 2%
  typing : 6.600s, 53%
```

I re-tried to run the nightly compilation server.
The issue is that now, when I run the compilation server I get this error `Error: /bin/sh: haxelib: command not found` (thanks to El Capitan I guess).

**Comment by ncannasse** [comment]
Try to compile with -v and check if you get a lag while typing one specific function

**Comment by fantoine** [comment]
The haxelib error seems more related to my IDE than to haxe.
So I successfully started it by hand and the issue I mentioned in the topic (`/usr/local/lib/haxe/std/StdTypes.hx:119: characters 7-35 : Duplicate metadata 'interface'`) ran away.

I don't really see specific long lags except on a file from my project and on [js/node/fs/WriteStream.hx](https://github.com/HaxeFoundation/hxnodejs/blob/d25c1536b20edcd018b43d44d2b2fa47bfd3b6c7/src/js/node/fs/WriteStream.hx) which is however not very complex.
But really it's only a question of ms...

**Comment by fantoine** [comment]
After some more compilations, the 'Duplicate metadata' came back:
`/usr/local/lib/haxe/std/StdTypes.hx:123: characters 7-35 : Duplicate metadata 'interface'`

**Comment by back2dos** [comment]
Meh. This may be caused by `tink_syntaxhub` in fact, which becomes slow with deep package paths. That's because of how `Context.onTypeNotFound` is invoked. Suppose you reference `Array` in `foo.bar.baz.blub.Frozzle`, then the compiler will invoke `Context.onTypeNotFound` for `foo.bar.baz.blub.Array`, then for `foo.bar.baz.Array`, then for `foo.bar.Array`, then for `foo.Array` and then will actually use the top-level class. That means using top-level types from deeply nested types becomes slow, because any frontend plugins will hit the file system a lot of times to check if there is something else there. I have just added a cache to `tink_syntaxhub` that might help fixing the problem. Could you update the lib and measure again to see if we're moving in the right direction?

**Comment by fantoine** [comment]
I get a small improvement on tink_syntaxhub but it doesn't impact the typing time:

````
Total time : 12.520s
------------------------------------
  analyzer-cleanup : 0.000s, 0%
  analyzer-const-propagation : 0.130s, 1%
  analyzer-copy-propagation : 0.020s, 0%
  analyzer-filter-apply : 0.000s, 0%
  analyzer-from-texpr : 0.030s, 0%
  analyzer-fusion : 0.010s, 0%
  analyzer-local-dce : 0.020s, 0%
  analyzer-ssa-apply : 0.060s, 0%
  analyzer-to-texpr : 0.000s, 0%
  filters : 0.120s, 1%
  generate js : 0.040s, 0%
  haxelib : 0.000s, 0%
  macro _hxnodejs.VersionWarning.include : 0.000s, 0%
  macro afterGenerate : 0.160s, 1%
  macro fab.Async.build : 0.070s, 1%
  macro fab.api.db.DatabaseBuilder.addRepositories : 0.000s, 0%
  macro fab.api.db.DatabaseBuilder.build : 0.100s, 1%
  macro fab.api.doc.SwaggerBuilder.addModelPath : 0.000s, 0%
  macro fab.api.doc.SwaggerBuilder.enable : 0.010s, 0%
  macro fab.api.i18n.LocalizatorBuilder.addTranslationPath : 0.000s, 0%
  macro fab.api.i18n.LocalizatorBuilder.build : 0.020s, 0%
  macro fab.api.macro.MacroTools.listClassesName : 0.000s, 0%
  macro fab.api.macro.MacroTools.readFileLines : 0.020s, 0%
  macro fab.api.routing.Route.send : 0.010s, 0%
  macro fab.api.routing.RouterBuilder.addRoutes : 0.000s, 0%
  macro fab.api.routing.RouterBuilder.build : 0.150s, 1%
  macro fab.api.test.TesterBuilder.addFixtures : 0.000s, 0%
  macro fab.api.test.TesterBuilder.addTests : 0.000s, 0%
  macro fab.api.test.TesterBuilder.build : 0.160s, 1%
  macro fab.api.validation.ValidationBuilder.enable : 0.000s, 0%
  macro haxe.macro.Compiler.allowPackage : 0.000s, 0%
  macro haxe.macro.Compiler.keep : 0.000s, 0%
  macro mcli.internal.Macro.build : 0.010s, 0%
  macro minject.Injector.getValue : 0.000s, 0%
  macro minject.Injector.instantiate : 0.000s, 0%
  macro minject.Injector.map : 0.130s, 1%
  macro minject.InjectorMacro.addMetadata : 0.010s, 0%
  macro minject.InjectorMapping.toSingleton : 0.280s, 2%
  macro npm.Include.build : 0.070s, 1%
  macro onGenerate : 0.070s, 1%
  macro tink.SyntaxHub.build : 0.300s, 2%
  macro tink.SyntaxHub.use : 0.000s, 0%
  macro tink.Template.addFlavor : 0.000s, 0%
  macro tink.Template.use : 0.000s, 0%
  macro typing (+init) : 1.010s, 8%
  macro util.CopyMethods.build : 0.000s, 0%
  macro util.Mongoose.buildManager : 0.000s, 0%
  macro util.Mongoose.buildModel : 0.260s, 2%
  other : 1.750s, 14%
  parsing : 0.240s, 2%
  typing : 7.260s, 58%
[Finished in 12.6s]
```

**Comment by back2dos** [comment]
Ok, I've tried another thing, can you update and measure again please?

**Comment by fantoine** [comment]
Definitly looks better! :)

I think compile timing looks more normal now.

```
Total time : 3.770s
------------------------------------
  analyzer-cleanup : 0.000s, 0%
  analyzer-const-propagation : 0.100s, 3%
  analyzer-copy-propagation : 0.080s, 2%
  analyzer-filter-apply : 0.000s, 0%
  analyzer-from-texpr : 0.020s, 1%
  analyzer-fusion : 0.030s, 1%
  analyzer-local-dce : 0.030s, 1%
  analyzer-ssa-apply : 0.050s, 1%
  analyzer-to-texpr : 0.000s, 0%
  filters : 0.120s, 3%
  generate js : 0.060s, 2%
  haxelib : 0.000s, 0%
  macro _hxnodejs.VersionWarning.include : 0.000s, 0%
  macro afterGenerate : 0.170s, 5%
  macro fab.Async.build : 0.070s, 2%
  macro fab.api.db.DatabaseBuilder.addRepositories : 0.000s, 0%
  macro fab.api.db.DatabaseBuilder.build : 0.000s, 0%
  macro fab.api.doc.SwaggerBuilder.addModelPath : 0.000s, 0%
  macro fab.api.doc.SwaggerBuilder.enable : 0.010s, 0%
  macro fab.api.i18n.LocalizatorBuilder.addTranslationPath : 0.000s, 0%
  macro fab.api.i18n.LocalizatorBuilder.build : 0.020s, 1%
  macro fab.api.macro.MacroTools.listClassesName : 0.000s, 0%
  macro fab.api.macro.MacroTools.readFileLines : 0.010s, 0%
  macro fab.api.routing.Route.send : 0.000s, 0%
  macro fab.api.routing.RouterBuilder.addRoutes : 0.000s, 0%
  macro fab.api.routing.RouterBuilder.build : 0.050s, 1%
  macro fab.api.test.TesterBuilder.addFixtures : 0.000s, 0%
  macro fab.api.test.TesterBuilder.addTests : 0.000s, 0%
  macro fab.api.test.TesterBuilder.build : 0.010s, 0%
  macro fab.api.validation.ValidationBuilder.enable : 0.000s, 0%
  macro haxe.macro.Compiler.allowPackage : 0.000s, 0%
  macro haxe.macro.Compiler.keep : 0.000s, 0%
  macro mcli.internal.Macro.build : 0.020s, 1%
  macro minject.Injector.getValue : 0.000s, 0%
  macro minject.Injector.instantiate : 0.000s, 0%
  macro minject.Injector.map : 0.060s, 2%
  macro minject.InjectorMacro.addMetadata : 0.000s, 0%
  macro minject.InjectorMapping.toSingleton : 0.130s, 3%
  macro npm.Include.build : 0.090s, 2%
  macro onGenerate : 0.070s, 2%
  macro tink.SyntaxHub.build : 0.430s, 11%
  macro tink.SyntaxHub.use : 0.000s, 0%
  macro tink.Template.addFlavor : 0.000s, 0%
  macro tink.Template.use : 0.000s, 0%
  macro typing (+init) : 0.950s, 25%
  macro util.CopyMethods.build : 0.010s, 0%
  macro util.Mongoose.buildManager : 0.000s, 0%
  macro util.Mongoose.buildModel : 0.010s, 0%
  other : 0.280s, 7%
  parsing : 0.340s, 9%
  typing : 0.550s, 15%
[Finished in 4.0s]
```

**Comment by back2dos** [comment]
Ok, great. The underlying issue is easy to tackle. In fact this change to `Context.onTypeNotFound` would already do it:

```haxe
public static function onTypeNotFound ( callback : String -> TypeDefinition ) {
  var cache = new Map();
  load("on_type_not_found",1)(funtion (type) {
    if (!cache.exists(type)) cache[type] = callback();
    return cache[type];
  });
}
```

This is based of course on the assumption that a custom type resolver that returns nothing for a type once, will do it again. I think that's fair enough. It may be wise to put this into `on_type_not_found` itself.

As for the `Duplicate metadata 'interface'` I am as clueless as the next guy.

**Comment by Simn** [comment]
Any chance you could figure out where the "Duplicate interface" error comes from? I've heard about this before but nobody could figure out the cause yet.

**Comment by kevinresol** [comment]
@Simn  I have the "Duplicate interface" error on my machine, what can I do to trace it?

**Comment by Simn** [comment]
I wish I knew. Does it involve OpenFL?

**Comment by kevinresol** [comment]
No, I'm using ufront, the error only appears when using compilation server

**Comment by Simn** [comment]
Do you know how to build Haxe/ I can commit some debug information to a branch so we can figure this out.

**Comment by kevinresol** [comment]
Haven't tried before but I think I can sort it out.
Btw I cannot use latest dev branch because of https://github.com/HaxeFoundation/haxe/issues/4843

**Comment by kevinresol** [comment]
Before doing anything, let me write down some points to note first:

1. My code involves type building macro
2. The bug only appears when using compilation server
3. The first build is good (after starting the server)
4. The second build fails with `Type name model.UserClientData is redefined from module model.UserClientData` where `model.UserClientData` is the type built with macro
5. I comment out the type building macro, the build fails with `Type not found : model.UserClientData`
6. uncomment the code, the build fails with `Duplicate metadata 'interface'`

@Simn I am not available at this very moment, will be back in an hour and test the dev build regarding to #4843

**Comment by Simn** [comment]
That makes me suspect your build macros. The compilation server keeps some state between compilations, so if you run the same macro twice it would build the same type twice, leading to the observed error. In fact, the duplicate metadata error could occur for the same reason: A macro adds it during the first compilation and then again during the second one. It's up to the implementer to consider that.

**Comment by kevinresol** [comment]
`/usr/local/lib/haxe/std/StdTypes.hx:119: characters 7-35 : Duplicate metadata 'interface'`

It occurs in the std library, not sure if it is really related to user code

**Comment by Simn** [comment]
What exactly does that point to?

**Comment by kevinresol** [comment]
`extern interface ArrayAccess<T> { }`

btw what my build macro does is basically read a typedef of anon obj and then build another typedef of anon obj (almost 1 to 1 copy with slight type change). No metadata involved.

**Comment by Simn** [comment]
What target are you compiling to?

I don't think this comes from the compiler, I cannot find any notion of an "interface" metadata.

**Comment by kevinresol** [comment]
js

**Comment by gamedevsam** [comment]
This issue is getting off track, also seems like it was already resolved?

**Comment by kevinresol** [comment]
I have updated to latest build (4e53627) and the problem of compilation server has changed slightly (only last step is different):

0. The first build is good (after starting the server)
0. The second build fails with Type name model.UserClientData is redefined from module model.UserClientData where model.UserClientData is the type built with macro
0. I comment out the type building macro, the build fails with Type not found : model.UserClientData
0. uncomment the code, the build fails with `/Users/kevin/Development/haxelib/minject/2,0,0-rc,1/src/lib/minject/point/PropertyInjectionPoint.hx:33: characters 2-46 : Local variable tmp used without being initialized` ([Source](https://github.com/massiveinteractive/minject/blob/master/src/lib/minject/point/PropertyInjectionPoint.hx#L33))

**Comment by ncannasse** [comment]
I'm pretty sure the issues are minject-related, but let's continue that one another thread given that the original issue (typing time) got resolved already.

**Comment by kevinresol** [comment]
This is still unresolved. The `Duplicate metadata` problem is still there.
Search around all source code, the only place I can find a "Duplicate metadata" is in [codegen.ml](https://github.com/HaxeFoundation/haxe/blob/b5a728976ef264f21ca5b500eb5e49832031ddb8/src/generators/codegen.ml#L162)

**Comment by ncannasse** [comment]
Please open another issue with if possible a reproducible example
