### ISSUE TITLE
[C++] Compilation error using Callable

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5584]
Using the latest development build of Haxe, we are seeing a new error during C++ compilation.

     error C2440: 'type cast': cannot convert from 'Dynamic' to 'hx::Object *'

Where this occurs is where we are using CFFI. I have this reproduction case, which appears to result the same error (during a release build), and does not error when built using Haxe 3.3.0-rc1

```haxe
import cpp.Callable;
import cpp.Object;
import haxe.io.Bytes;


class Main {
	
	
	public static function main () {
		
		var callable = new Callable<Object->Object>(cffi_decompress);
		
		var bytes = Bytes.alloc (100);
		
		var data:Dynamic = callable.call (bytes);
		
	}
	
	
	/* This is not the exact signature, we are actually loading
	 * using CFFI Prime, but this reproduces the same error
	 * (occurring in latest dev, not in RC1)
	 */
	private static function cffi_decompress (a:Dynamic):Dynamic {
		
		return null;
		
	}
	
	
}
```

```
-main Main
-cpp bin
```

I am not sure why `-debug` makes this small code sample work, the error that occurs in our real-world code happens with or without `-debug`.

The return type from `cpp.Prime.loadPrime` is `Dynamic`, I suspect it is a combination of a `Dynamic` function reference, and `cpp.Callable` using C++ object types (`cpp.Void`, `cpp.Object`, etc)

If this occurs for the reason I suspect, then we can unwrap the `loadPrime` method and generate our own static version of each function signature in a macro, but this is a regression for us from 3.2.1 and 3.3.0-rc1, and perhaps there is a better fix for this on the gencpp or HXCPP side.

Thank you!

**Comment by Gama11** [comment]
@hughsando it seems like you fixed this in 4d133d2? Can this issue be closed?

**Comment by hughsando** [comment]
I fixed one part of it - should be ok as far as this report goes.
But I have a real problem with the callable class, get_call, when the
variable is static (not a local var) - -it puts the "this" in a temp.
And this breaks things, because I was using this call as a way of telling
haxe the type of the variable (function), while telling cpp what it really
is (cpp::Function).
You actually don't need the "call" bit anymore, and what I realy want is
the abstract to return itself (ie, the abstract) not the "this" (its
implementation variable).  Or alternatively, the the compiler to never temp
the call property variable.

**Comment by Gama11** [comment]
@hughsando Are you sure this is fixed? The test case now fails to compile again for me on 59439c7 with the same error as before:

```
./src/Main.cpp(32): error C2440: 'type cast': cannot convert from 'Dynamic' to 'hx::Object *'
./src/Main.cpp(32): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
Error: Build failed
```

One commit earlier, on bcd544a, it compiles.

**Comment by Gama11** [comment]
Since 59439c7, I'm now seeing these failures in Flixel's Travis for latest Haxe dev:

```
/home/travis/haxe/lib/lime/2,9,1/lime/utils/Bytes.hx:88: characters 23-94 : You cannot access the cpp package while targeting flash (for cpp.Callable)
```

https://travis-ci.org/HaxeFlixel/flixel/jobs/157295120

**Comment by Gama11** [comment]
Alright, with 63a2350,

- Flixel's Travis is green again
- I don't get the Travis error locally anymore either

However, I still get the `cannot convert from 'Dynamic' to 'hx::Object *'` error when trying to compile Joshua's isolated test case, as well as when I try to compile a Flixel project with `-Dnext` (Flixel's Travis doesn't test this right now).

**Comment by Gama11** [comment]
Forget what I said actually, I made a mistake when updating the Haxe install on Windows - everything appears to be working again! :+1: I also added Joshua's unit test to Haxe's test suite and it passed Travis: https://travis-ci.org/Gama11/haxe/builds/157575368
