### ISSUE TITLE
Eval interp errors

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6273]
Two errors I found while trying eval interp:

- `Context.signature` is not working correctly : In castledb case I'm creating abstract types and I want to compare two type structures to define a single abstract in case they are the same. So I'm using Context.signature on an array of (string,enum) value and if there's already a match I'm creating a typedef instead of redefining a new abstract. I think it's a quite useful feature to be able to make a hashing of any value, since trying to do it in Haxe would be a lot of code and uses a lot of CPU at the interp level

- Runtime error with a Heaps sample (using HL runtime): `Can't cast enum<hxsl.Type> to enum<haxe.macro.Binop>` while unserializing a Shader. Shader are serialized within macro using haxe.Serialize, so there might be something wrong going there.

**Comment by ncannasse** [comment]
Another one: using `$v{enumValue}` I get an error `hxbit/Macros.hx:115: characters 17-20 : Type not found : hxbit.PropTypeDesc`, I think the enum path is not correctly print since it should be hxbit.Macros.PropTypeDesc

**Comment by nadako** [comment]
> I think the enum path is not correctly print since it should be hxbit.Macros.PropTypeDesc

@Simn is there a way to get module path for a given `VEnumValue`?

**Comment by Simn** [comment]
We'll have to dig up the module def from ctx.type_cache and do the usual path dance.

**Comment by Simn** [comment]
How do I reproduce that Heaps sample failure?

**Comment by Simn** [comment]
* I've implemented Context.signature. It's weird, but it does produce a signature...
* Fixed the enum path problem.
* Need more information on the heaps serialization problem.

**Comment by ncannasse** [comment]
With Heaps, just compiling and running an sample with HL should trigger the issue.
Minimal setup:

```
// haxe -lib heaps -lib hlsdl -main Test
class Test extends hxd.App {
   static function main() {
       new Test();
   }
}
```

hlsdl needs to be `haxelib dev` from (hl/libs/sdl)

**Comment by ncannasse** [comment]
I tried the latest branch, it works good:

Full recompilation:
interp 27.4 s ( 14.7 s macros)
eval 16.3 s ( 3.4 s macros)

Partial recompilation (change one file quite central file with compilation server)
interp 10.1 s ( 2.1 s macros )
eval 8.5 ( 0.7 s macros )

Still good because we get a 15% speedup using compilation server.

However, it still does not work correctly at runtime (some shader problems causing some invalid display although no runtime error is triggered). Will post there what I find when I compare the outputs

**Comment by ncannasse** [comment]
Ok I can confirm our Northgard ground shader is broken with Eval macros, I'll send it privately to @Simn for debugging purposes

**Comment by ncannasse** [comment]
I have located the issue (although not the cause).
In the serialized shader, the inputs (@input shader variables) are in the order [dirtBlend, cliffBlend, waterZ, forestBlend] using Eval while the correct order (which should be the same as the original shader source) is [dirtBlend, forestBlend, cliffBlend, waterZ]

This lead to buffer values being wrongly bounded and having different rendering

**Comment by ncannasse** [comment]
I can see that in Checker.hx we are using a Map then listing the vars with Lambda.array(varMap). There might be a difference of ordering between Eval and Interp, looking at fixing now since it's not a correct assumption.

**Comment by ncannasse** [comment]
Fixed ! will try to reproduce #6308 now
