### ISSUE TITLE
Null Safety: should `Dynamic` not accept nullable values?

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9588]
I ran into this because `Std.string(somethingNullable)` produces an error. I'd say that's a bit over the top. One option would be to make `Std.string` accept `Null<Dynamic>` but since `Dynamic` is the type system's finest landmine, I wonder if null safety should not accept passing nullable expressions to it.

**Comment by Simn** [comment]
That might be two separate issues because `Std.string` is specified to work with `null` just fine.

**Comment by RealyUniqueName** [comment]
I think `Dynamic` by itself should not imply `null` is acceptable. OTOH that could simplify  transition of std lib to safety.

**Comment by sebthom** [comment]
What is the approach to come to a decision here? I too think Dynamic should not imply null-ability and since this technically is the case by the current implementation, can we please just get started progressively updating stdlib accordingly?

**Comment by Simn** [comment]
Imposing this restriction on `Dynamic` of all things seems impractical and annoying. It has been specified to accept any value, and that should include `null`.

**Comment by sebthom** [comment]
Ok, fine with me too. When can we expect a change of the null-safety checker in this regard? The current situation makes the usage of null-safety with stdlib very impractial if not impossible.

**Comment by Gama11** [comment]
Will `Any` still be non-nullable at least?

**Comment by RealyUniqueName** [comment]
I agree `Any` should stay non-nullable as a stricter replacement for `Dynamic`

**Comment by Simn** [comment]
Yes that seems fine.

**Comment by RealyUniqueName** [comment]
> Ok, fine with me too. When can we expect a change of the null-safety checker in this regard?

I'll try it later this week.

**Comment by RealyUniqueName** [comment]
Sorry for such a long delay.
I've pushed a change which allows passing nullable values to `Dynamic`.

But that arises a question: should `Dynamic` be treated as a nullable type in all cases now?
For example should this fail?
```haxe
var d:Dynamic = someValue();
var s:String = d; // Should this fail? Because `d` can contain `null`.
```
If we treat `Dynamic` as a way to "disable" type system, then that _should not_ fail. But if we treat `Dynamic` as just a nulalble type, then that _should_ fail.

**Comment by RblSb** [comment]
I think the decision that `Dynamic` can be `null` was made and this can be closed.

**Comment by Simn** [comment]
I'm seeing lots of these errors when compiling the vshaxe language server (not vshaxe itself):

```
[ERROR] src/haxeLanguageServer/features/CompletionFeature.hx:20: characters 3-81

  20 |   context.languageServerProtocol.onRequest(CompletionRequest.type, onCompletion);
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Null safety: Null<haxe.extern.EitherType<Array<languageServerProtocol.CompletionItem>, languageServerProtocol.CompletionList>> should be Dynamic
```

I'm not sure if it's exactly the same issue but it seems related. Does that reproduce for you too?

**Comment by RblSb** [comment]
I thought this is display-only, because i can compile full vshaxe with vshaxe-build, that's strange https://github.com/HaxeFoundation/haxe/issues/12459
Basic NS errors still reported in full build like nullableString.charAt access in server code, but these are not reported somewhat, until i compile server separately.

**Comment by Simn** [comment]
It happens when I try to compile this file: https://github.com/vshaxe/haxe-language-server/blob/master/build.hxml
